package neo4j

import (
	"fmt"
	"strings"

	"ontologypipeline/internal/types"
)

// Result holds the generated Neo4j schema artifacts.
type Result struct {
	SchemaCypher string // Cypher statements for constraints and indexes
	SyncConfig   string // YAML config for PG→Neo4j sync
}

// Generate produces Neo4j schema (constraints, indexes) and sync configuration.
func Generate(o *types.Ontology) *Result {
	var cypher strings.Builder
	var syncCfg strings.Builder

	schema := strings.ReplaceAll(o.ID, "_", "")

	cypher.WriteString(fmt.Sprintf("// Generated by Ontology Pipeline from %s v%s\n", o.Name, o.Version))
	cypher.WriteString("// Neo4j constraints and indexes\n\n")

	syncCfg.WriteString(fmt.Sprintf("# Sync config for %s v%s\n", o.Name, o.Version))
	syncCfg.WriteString(fmt.Sprintf("schema: %s\n", schema))
	syncCfg.WriteString("\nnodes:\n")

	for _, c := range o.Classes {
		label := toPascalCase(c.ID)

		// Unique constraint on id
		cypher.WriteString(fmt.Sprintf("CREATE CONSTRAINT %s_id_unique IF NOT EXISTS FOR (n:%s) REQUIRE n.id IS UNIQUE;\n", label, label))

		// Indexes on enum and boolean attributes that are commonly filtered
		for _, a := range c.Attributes {
			if a.Type == "enum" || a.Type == "boolean" {
				propName := toCamelCase(a.ID)
				cypher.WriteString(fmt.Sprintf("CREATE INDEX %s_%s_idx IF NOT EXISTS FOR (n:%s) ON (n.%s);\n", label, propName, label, propName))
			}
		}

		// Sync config entry
		syncCfg.WriteString(fmt.Sprintf("  - label: %s\n", label))
		syncCfg.WriteString(fmt.Sprintf("    table: %s.%s\n", schema, pluralize(c.ID)))
		syncCfg.WriteString("    properties:\n")
		syncCfg.WriteString("      - id\n")
		for _, a := range c.Attributes {
			syncCfg.WriteString(fmt.Sprintf("      - %s\n", toCamelCase(a.ID)))
		}
	}

	// Relationship indexes
	cypher.WriteString("\n// Relationship indexes\n")
	for _, r := range o.Relationships {
		edgeType := strings.ToUpper(r.ID)
		cypher.WriteString(fmt.Sprintf("// %s: (%s)-[:%s]->(%s)\n",
			r.Name, toPascalCase(r.From), edgeType, toPascalCase(r.To)))
	}

	syncCfg.WriteString("\nrelationships:\n")
	for _, r := range o.Relationships {
		syncCfg.WriteString(fmt.Sprintf("  - type: %s\n", strings.ToUpper(r.ID)))
		syncCfg.WriteString(fmt.Sprintf("    from: %s\n", toPascalCase(r.From)))
		syncCfg.WriteString(fmt.Sprintf("    to: %s\n", toPascalCase(r.To)))
		syncCfg.WriteString(fmt.Sprintf("    cardinality: %s\n", r.Cardinality))
		if len(r.EdgeAttributes) > 0 {
			syncCfg.WriteString("    edge_properties:\n")
			for _, ea := range r.EdgeAttributes {
				syncCfg.WriteString(fmt.Sprintf("      - %s\n", toCamelCase(ea.ID)))
			}
		}
	}

	return &Result{
		SchemaCypher: cypher.String(),
		SyncConfig:   syncCfg.String(),
	}
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

var irregularPlurals = map[string]string{
	"equipment": "equipment",
	"inventory": "inventory",
	"staff":     "staff",
}

func pluralize(s string) string {
	if p, ok := irregularPlurals[s]; ok {
		return p
	}
	parts := strings.Split(s, "_")
	lastWord := parts[len(parts)-1]
	if p, ok := irregularPlurals[lastWord]; ok {
		parts[len(parts)-1] = p
		return strings.Join(parts, "_")
	}
	if strings.HasSuffix(s, "ss") || strings.HasSuffix(s, "sh") || strings.HasSuffix(s, "ch") || strings.HasSuffix(s, "x") || strings.HasSuffix(s, "z") {
		return s + "es"
	}
	if strings.HasSuffix(s, "s") {
		return s
	}
	if strings.HasSuffix(s, "y") && len(s) > 1 {
		prev := s[len(s)-2]
		if prev != 'a' && prev != 'e' && prev != 'i' && prev != 'o' && prev != 'u' {
			return s[:len(s)-1] + "ies"
		}
	}
	return s + "s"
}
