package tsgen

import (
	"fmt"
	"strings"
	"unicode"

	"ontologypipeline/internal/types"
)

// Generate produces TypeScript interface definitions from an ontology.
func Generate(o *types.Ontology) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("// Generated by Ontology Pipeline from %s v%s\n", o.Name, o.Version))
	b.WriteString("// Do not edit manually — edit the ontology YAML and re-run the pipeline.\n\n")

	// Build relationship lookup: classID → list of FK fields
	fkFields := buildFKFields(o.Relationships)

	for i, c := range o.Classes {
		if i > 0 {
			b.WriteString("\n")
		}
		b.WriteString(generateInterface(c, fkFields))
	}

	// Generate enum types
	enums := collectEnums(o.Classes)
	if len(enums) > 0 {
		b.WriteString("\n// ============================================================\n")
		b.WriteString("// Enum Types\n")
		b.WriteString("// ============================================================\n\n")
		for _, e := range enums {
			b.WriteString(e)
			b.WriteString("\n")
		}
	}

	return b.String()
}

type fkField struct {
	FieldName string // e.g., "sparePartId"
	TSType    string // always "string"
	Comment   string // relationship description
}

func buildFKFields(rels []types.Relationship) map[string][]fkField {
	result := make(map[string][]fkField)
	for _, r := range rels {
		switch r.Cardinality {
		case "many_to_one":
			field := fkField{
				FieldName: toCamelCase(r.To + "_id"),
				TSType:    "string",
				Comment:   r.Description,
			}
			result[r.From] = append(result[r.From], field)
		case "one_to_one":
			field := fkField{
				FieldName: toCamelCase(r.To + "_id"),
				TSType:    "string",
				Comment:   r.Description,
			}
			result[r.From] = append(result[r.From], field)
		case "one_to_many":
			field := fkField{
				FieldName: toCamelCase(r.From + "_id"),
				TSType:    "string",
				Comment:   r.Description,
			}
			result[r.To] = append(result[r.To], field)
		}
	}
	return result
}

func generateInterface(c types.Class, fkFields map[string][]fkField) string {
	var b strings.Builder
	interfaceName := toPascalCase(c.ID)

	if c.Description != "" {
		b.WriteString(fmt.Sprintf("/** %s */\n", c.Description))
	}
	b.WriteString(fmt.Sprintf("export interface %s {\n", interfaceName))

	// id field
	b.WriteString("  id: string\n")

	// Regular attributes
	for _, a := range c.Attributes {
		if a.ID == "created_at" || a.ID == "updated_at" {
			continue
		}
		tsType := mapTSType(a)
		fieldName := toCamelCase(a.ID)
		optional := ""
		if a.Derived != "" || (!a.Required && a.Default == nil) {
			optional = " | null"
		}
		b.WriteString(fmt.Sprintf("  %s: %s%s\n", fieldName, tsType, optional))
	}

	// FK fields from relationships
	if fks, ok := fkFields[c.ID]; ok {
		for _, fk := range fks {
			b.WriteString(fmt.Sprintf("  %s: %s\n", fk.FieldName, fk.TSType))
		}
	}

	// Timestamps
	b.WriteString("  createdAt: string\n")
	b.WriteString("  updatedAt: string\n")

	b.WriteString("}\n")
	return b.String()
}

func mapTSType(a types.Attribute) string {
	switch a.Type {
	case "integer", "decimal":
		return "number"
	case "boolean":
		return "boolean"
	case "enum":
		if len(a.EnumValues) > 0 {
			quoted := make([]string, len(a.EnumValues))
			for i, v := range a.EnumValues {
				quoted[i] = fmt.Sprintf("'%s'", v)
			}
			return strings.Join(quoted, " | ")
		}
		return "string"
	case "string", "text", "date", "datetime":
		return "string"
	default:
		return "string"
	}
}

func collectEnums(classes []types.Class) []string {
	var result []string
	seen := make(map[string]bool)
	for _, c := range classes {
		for _, a := range c.Attributes {
			if a.Type == "enum" && len(a.EnumValues) > 0 {
				typeName := toPascalCase(a.ID)
				if seen[typeName] {
					continue
				}
				seen[typeName] = true
				quoted := make([]string, len(a.EnumValues))
				for i, v := range a.EnumValues {
					quoted[i] = fmt.Sprintf("'%s'", v)
				}
				result = append(result, fmt.Sprintf("export type %s = %s", typeName, strings.Join(quoted, " | ")))
			}
		}
	}
	return result
}

// toCamelCase converts snake_case to camelCase.
func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// toPascalCase converts snake_case to PascalCase.
func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			runes := []rune(parts[i])
			runes[0] = unicode.ToUpper(runes[0])
			parts[i] = string(runes)
		}
	}
	return strings.Join(parts, "")
}
