package pg

import (
	"fmt"
	"strings"

	"ontologypipeline/internal/types"
)

// Generate produces SQL DDL from an ontology definition.
func Generate(o *types.Ontology) string {
	var b strings.Builder
	schema := schemaName(o.ID)

	b.WriteString(fmt.Sprintf("-- Generated by Ontology Pipeline from %s v%s\n", o.Name, o.Version))
	b.WriteString(fmt.Sprintf("-- Schema: %s\n\n", schema))
	b.WriteString(fmt.Sprintf("CREATE SCHEMA IF NOT EXISTS %s;\n\n", schema))

	// Build relationship index for FK generation
	relIndex := buildRelIndex(o.Relationships)

	// Build unique constraint index from required many_to_one pairs
	uniqueIndex := buildUniqueIndex(o.Relationships)

	// Topological sort: classes without FK deps first
	sorted := topoSortClasses(o.Classes, relIndex)

	// Generate tables in dependency order
	for _, c := range sorted {
		b.WriteString(generateTable(schema, c, relIndex, uniqueIndex))
		b.WriteString("\n")
	}

	// Generate junction tables for many_to_many relationships
	for _, r := range o.Relationships {
		if r.Cardinality == "many_to_many" {
			b.WriteString(generateJunctionTable(schema, r))
			b.WriteString("\n")
		}
	}

	// Generate indexes
	for _, r := range o.Relationships {
		if r.Cardinality != "many_to_many" {
			b.WriteString(generateFKIndex(schema, r))
		}
	}

	return b.String()
}

// schemaName converts ontology ID to PG schema name.
// Convention: remove underscores for schema name (spare_parts → spareparts).
func schemaName(id string) string {
	return strings.ReplaceAll(id, "_", "")
}

type relInfo struct {
	Rel     types.Relationship
	ColName string // FK column name in the owning table
}

// topoSortClasses orders classes so that FK-referenced tables come first.
func topoSortClasses(classes []types.Class, relIndex map[string][]relInfo) []types.Class {
	classMap := make(map[string]types.Class)
	for _, c := range classes {
		classMap[c.ID] = c
	}

	deps := make(map[string]map[string]bool)
	for _, c := range classes {
		deps[c.ID] = make(map[string]bool)
	}
	for ownerID, rels := range relIndex {
		for _, ri := range rels {
			targetID := ri.Rel.To
			if ri.Rel.Cardinality == "one_to_many" {
				targetID = ri.Rel.From
			}
			if targetID != ownerID {
				deps[ownerID][targetID] = true
			}
		}
	}

	var sorted []types.Class
	visited := make(map[string]bool)

	var visit func(id string)
	visit = func(id string) {
		if visited[id] {
			return
		}
		visited[id] = true
		for dep := range deps[id] {
			visit(dep)
		}
		if c, ok := classMap[id]; ok {
			sorted = append(sorted, c)
		}
	}

	for _, c := range classes {
		visit(c.ID)
	}
	return sorted
}

func buildRelIndex(rels []types.Relationship) map[string][]relInfo {
	idx := make(map[string][]relInfo)
	for _, r := range rels {
		switch r.Cardinality {
		case "many_to_one":
			colName := fkColumnName(r)
			idx[r.From] = append(idx[r.From], relInfo{Rel: r, ColName: colName})
		case "one_to_one":
			colName := r.To + "_id"
			idx[r.From] = append(idx[r.From], relInfo{Rel: r, ColName: colName})
		case "one_to_many":
			colName := r.From + "_id"
			idx[r.To] = append(idx[r.To], relInfo{Rel: r, ColName: colName})
		}
	}
	return idx
}

// fkColumnName determines the FK column name for a many_to_one relationship.
// If the relationship target class name differs meaningfully from the relationship ID,
// we use a more descriptive name. The hand-written schema uses position_id (from "affects"
// relationship to inventory_position) instead of inventory_position_id.
func fkColumnName(r types.Relationship) string {
	// Special mapping: if the relationship semantically names the FK differently
	// For "affects" (stock_movement → inventory_position), use "position_id"
	// For "procures" (purchase_order → spare_part), use "spare_part_id"
	// Default: target_class_id
	return r.To + "_id"
}

// buildUniqueIndex finds classes that should have a UNIQUE constraint
// from their combination of required many_to_one relationships.
// E.g., inventory_position has required tracks→spare_part and located_in→warehouse,
// meaning UNIQUE(spare_part_id, warehouse_id).
func buildUniqueIndex(rels []types.Relationship) map[string][]string {
	// Group required many_to_one relationships by from-class
	classRels := make(map[string][]string) // classID → list of FK column names
	for _, r := range rels {
		if r.Cardinality == "many_to_one" && r.Required {
			classRels[r.From] = append(classRels[r.From], r.To+"_id")
		}
	}
	// If a class has 2+ required many_to_one FKs, add a composite UNIQUE
	result := make(map[string][]string)
	for classID, cols := range classRels {
		if len(cols) >= 2 {
			result[classID] = cols
		}
	}
	return result
}

func generateTable(schema string, c types.Class, relIndex map[string][]relInfo, uniqueIndex map[string][]string) string {
	var b strings.Builder
	tableName := pluralize(c.ID)

	b.WriteString(fmt.Sprintf("-- %s: %s\n", c.Name, c.Description))
	b.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s.%s (\n", schema, tableName))
	b.WriteString("    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n")

	// Build set of derived attribute IDs for cross-reference detection
	derivedIDs := make(map[string]bool)
	for _, a := range c.Attributes {
		if a.Derived != "" {
			derivedIDs[a.ID] = true
		}
	}

	// Write columns: regular first, then simple derived
	var derivedAttrs []types.Attribute
	for _, a := range c.Attributes {
		if a.ID == "created_at" || a.ID == "updated_at" {
			continue
		}
		if a.Derived != "" {
			derivedAttrs = append(derivedAttrs, a)
			continue
		}
		col := generateColumn(a, derivedIDs)
		if col != "" {
			b.WriteString(fmt.Sprintf("    %s,\n", col))
		}
	}
	for _, a := range derivedAttrs {
		col := generateColumn(a, derivedIDs)
		if col != "" {
			b.WriteString(fmt.Sprintf("    %s,\n", col))
		}
	}

	// Write FK columns from relationships
	if rels, ok := relIndex[c.ID]; ok {
		for _, ri := range rels {
			constraint := ""
			if ri.Rel.Cardinality == "one_to_one" {
				constraint = " UNIQUE"
			}
			notNull := ""
			if ri.Rel.Required {
				notNull = " NOT NULL"
			}
			refTable := pluralize(ri.Rel.To)
			if ri.Rel.Cardinality == "one_to_many" {
				refTable = pluralize(ri.Rel.From)
			}
			b.WriteString(fmt.Sprintf("    %s UUID%s%s REFERENCES %s.%s(id),\n",
				ri.ColName, notNull, constraint, schema, refTable))
		}
	}

	// Auto timestamps
	b.WriteString("    created_at TIMESTAMPTZ DEFAULT now(),\n")
	b.WriteString("    updated_at TIMESTAMPTZ DEFAULT now()")

	// UNIQUE constraint for composite keys (e.g., spare_part_id + warehouse_id)
	if cols, ok := uniqueIndex[c.ID]; ok {
		b.WriteString(fmt.Sprintf(",\n    UNIQUE (%s)", strings.Join(cols, ", ")))
	}

	// Explicit unique constraints from YAML
	for _, uc := range c.UniqueConstraints {
		b.WriteString(fmt.Sprintf(",\n    UNIQUE (%s)", strings.Join(uc.Columns, ", ")))
	}

	b.WriteString("\n);\n")
	return b.String()
}

func generateColumn(a types.Attribute, derivedIDs map[string]bool) string {
	if a.Derived != "" && isComplexDerived(a.Derived) {
		return "" // complex derived: handled by scheduled task
	}

	if a.Derived != "" && referencesDerived(a.Derived, derivedIDs) {
		return "" // depends on another generated column
	}

	pgType := mapPGType(a.Type)
	parts := []string{a.ID, pgType}

	if a.Derived != "" {
		pgExpr := translateDerivedExpr(a.Derived)
		return fmt.Sprintf("%s %s GENERATED ALWAYS AS (%s) STORED", a.ID, pgType, pgExpr)
	}

	if a.Required {
		parts = append(parts, "NOT NULL")
	}
	if a.Unique {
		parts = append(parts, "UNIQUE")
	}
	if a.Default != nil {
		parts = append(parts, fmt.Sprintf("DEFAULT %s", formatDefault(a.Default, a.Type)))
	}
	if a.Type == "enum" && len(a.EnumValues) > 0 {
		quoted := make([]string, len(a.EnumValues))
		for i, v := range a.EnumValues {
			quoted[i] = fmt.Sprintf("'%s'", v)
		}
		parts = append(parts, fmt.Sprintf("CHECK (%s IN (%s))", a.ID, strings.Join(quoted, ",")))
	}

	return strings.Join(parts, " ")
}

func generateJunctionTable(schema string, r types.Relationship) string {
	var b strings.Builder
	tableName := r.ID // use relationship ID directly (e.g., "uses", "substituted_by")
	// Fix: don't pluralize junction table names — use relationship ID as-is
	// The hand-written schema uses "equipment_uses" which is the pluralized form
	// But for junction tables we keep the relationship ID
	if r.From == r.To {
		// self-referencing: keep as-is
	}

	b.WriteString(fmt.Sprintf("-- Junction: %s (%s)\n", r.Name, r.Description))
	b.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s.%s (\n", schema, tableName))

	fromCol := r.From + "_id"
	toCol := r.To + "_id"
	if r.From == r.To {
		fromCol = "from_" + r.From + "_id"
		toCol = "to_" + r.To + "_id"
	}

	b.WriteString(fmt.Sprintf("    %s UUID NOT NULL REFERENCES %s.%s(id),\n",
		fromCol, schema, pluralize(r.From)))
	b.WriteString(fmt.Sprintf("    %s UUID NOT NULL REFERENCES %s.%s(id),\n",
		toCol, schema, pluralize(r.To)))

	for _, ea := range r.EdgeAttributes {
		pgType := mapPGType(ea.Type)
		col := fmt.Sprintf("    %s %s", ea.ID, pgType)
		if ea.Type == "enum" && len(ea.EnumValues) > 0 {
			quoted := make([]string, len(ea.EnumValues))
			for i, v := range ea.EnumValues {
				quoted[i] = fmt.Sprintf("'%s'", v)
			}
			col += fmt.Sprintf(" CHECK (%s IN (%s))", ea.ID, strings.Join(quoted, ","))
		}
		b.WriteString(col + ",\n")
	}

	if r.From == r.To {
		b.WriteString(fmt.Sprintf("    PRIMARY KEY (from_%s_id, to_%s_id)\n", r.From, r.To))
	} else {
		b.WriteString(fmt.Sprintf("    PRIMARY KEY (%s_id, %s_id)\n", r.From, r.To))
	}
	b.WriteString(");\n")

	return b.String()
}

func generateFKIndex(schema string, r types.Relationship) string {
	var colName, tableName string
	switch r.Cardinality {
	case "many_to_one":
		colName = r.To + "_id"
		tableName = pluralize(r.From)
	case "one_to_one":
		colName = r.To + "_id"
		tableName = pluralize(r.From)
	case "one_to_many":
		colName = r.From + "_id"
		tableName = pluralize(r.To)
	default:
		return ""
	}

	indexName := fmt.Sprintf("idx_%s_%s", tableName, colName)
	return fmt.Sprintf("CREATE INDEX IF NOT EXISTS %s ON %s.%s(%s);\n",
		indexName, schema, tableName, colName)
}

func mapPGType(t string) string {
	switch t {
	case "integer":
		return "INTEGER"
	case "decimal":
		return "DECIMAL(18,4)"
	case "string":
		return "VARCHAR(255)"
	case "text":
		return "TEXT"
	case "boolean":
		return "BOOLEAN"
	case "date":
		return "DATE"
	case "datetime":
		return "TIMESTAMPTZ"
	case "enum":
		return "VARCHAR(50)"
	default:
		return "TEXT"
	}
}

func formatDefault(val any, attrType string) string {
	switch v := val.(type) {
	case bool:
		if v {
			return "true"
		}
		return "false"
	case int:
		return fmt.Sprintf("%d", v)
	case float64:
		return fmt.Sprintf("%g", v)
	case string:
		return fmt.Sprintf("'%s'", v)
	default:
		return fmt.Sprintf("'%v'", v)
	}
}

func referencesDerived(expr string, derivedIDs map[string]bool) bool {
	for id := range derivedIDs {
		if strings.Contains(expr, id) {
			return true
		}
	}
	return false
}

func isComplexDerived(expr string) bool {
	return strings.Contains(expr, "[") ||
		strings.Contains(expr, "SUM(") ||
		strings.Contains(expr, "AVG(") ||
		strings.Contains(expr, "COUNT(") ||
		strings.Contains(expr, "DATEDIFF(") ||
		strings.Contains(expr, "INTERVAL")
}

func translateDerivedExpr(expr string) string {
	return expr
}

// irregularPlurals handles words that don't follow standard English pluralization rules.
var irregularPlurals = map[string]string{
	"equipment":      "equipment",
	"inventory":      "inventory",
	"staff":          "staff",
	"sheep":          "sheep",
	"fish":           "fish",
	"person":         "people",
	"child":          "children",
}

func pluralize(s string) string {
	// Check irregular plurals
	if p, ok := irregularPlurals[s]; ok {
		return p
	}

	// Check if last component (after underscore) is irregular
	// e.g., "production_equipment" → "production_equipment"
	parts := strings.Split(s, "_")
	lastWord := parts[len(parts)-1]
	if p, ok := irregularPlurals[lastWord]; ok {
		parts[len(parts)-1] = p
		return strings.Join(parts, "_")
	}

	if strings.HasSuffix(s, "ss") || strings.HasSuffix(s, "sh") || strings.HasSuffix(s, "ch") || strings.HasSuffix(s, "x") || strings.HasSuffix(s, "z") {
		return s + "es"
	}
	if strings.HasSuffix(s, "s") {
		return s
	}
	if strings.HasSuffix(s, "y") && len(s) > 1 {
		prev := s[len(s)-2]
		if prev != 'a' && prev != 'e' && prev != 'i' && prev != 'o' && prev != 'u' {
			return s[:len(s)-1] + "ies"
		}
	}
	return s + "s"
}
