-- Generated by Ontology Pipeline from 简单CRM v1.0
-- Schema: simplecrm

CREATE SCHEMA IF NOT EXISTS simplecrm;

-- 客户: 
CREATE TABLE IF NOT EXISTS simplecrm.customers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    level VARCHAR(50) CHECK (level IN ('NORMAL','VIP','SVIP')),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 联系记录: 
CREATE TABLE IF NOT EXISTS simplecrm.contact_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contact_type VARCHAR(50) NOT NULL CHECK (contact_type IN ('PHONE','EMAIL','VISIT','ONLINE')),
    summary TEXT,
    contact_date TIMESTAMPTZ NOT NULL,
    customer_id UUID NOT NULL REFERENCES simplecrm.customers(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_contact_records_customer_id ON simplecrm.contact_records(customer_id);
