// Generated by Ontology Pipeline from 简单CRM v1.0
// Do not edit manually — edit the ontology YAML and re-run the pipeline.

export interface Customer {
  id: string
  name: string
  email: string | null
  level: 'NORMAL' | 'VIP' | 'SVIP' | null
  createdAt: string
  updatedAt: string
}

export interface ContactRecord {
  id: string
  contactType: 'PHONE' | 'EMAIL' | 'VISIT' | 'ONLINE'
  summary: string | null
  contactDate: string
  customerId: string
  createdAt: string
  updatedAt: string
}

// ============================================================
// Enum Types
// ============================================================

export type Level = 'NORMAL' | 'VIP' | 'SVIP'
export type ContactType = 'PHONE' | 'EMAIL' | 'VISIT' | 'ONLINE'
