package rules

import (
	"fmt"
	"strings"

	"ontologypipeline/internal/types"
)

// Result holds the generated rule engine artifacts.
type Result struct {
	ConfigYAML string // Rule engine configuration
	GoCode     string // Go rule engine skeleton
}

// Generate produces rule engine configuration and Go code skeleton.
func Generate(o *types.Ontology) *Result {
	var cfg strings.Builder
	var code strings.Builder

	cfg.WriteString(fmt.Sprintf("# Rule engine config for %s v%s\n", o.Name, o.Version))
	cfg.WriteString(fmt.Sprintf("# %d rules\n\n", len(o.Rules)))
	cfg.WriteString("rules:\n")

	code.WriteString("package rules\n\n")
	code.WriteString("// Generated by Ontology Pipeline — rule engine skeleton\n\n")
	code.WriteString("import (\n\t\"context\"\n\t\"log\"\n)\n\n")
	code.WriteString("type CheckResult struct {\n\tRuleID   string\n\tSeverity string\n\tMessage  string\n}\n\n")

	// Group rules by trigger type
	var beforeRules, afterRules, cronRules []types.Rule
	for _, r := range o.Rules {
		switch r.Trigger.Type {
		case "before_action":
			beforeRules = append(beforeRules, r)
		case "after_action":
			afterRules = append(afterRules, r)
		case "cron":
			cronRules = append(cronRules, r)
		}
	}

	// Config
	for _, r := range o.Rules {
		cfg.WriteString(fmt.Sprintf("  - id: %s\n", r.ID))
		cfg.WriteString(fmt.Sprintf("    name: %s\n", r.Name))
		cfg.WriteString(fmt.Sprintf("    trigger: %s\n", r.Trigger.Type))
		cfg.WriteString(fmt.Sprintf("    source: \"%s\"\n", strings.Join(r.Trigger.Source, ",")))
		cfg.WriteString(fmt.Sprintf("    entity: %s\n", r.Condition.Entity))
		cfg.WriteString(fmt.Sprintf("    condition: \"%s\"\n", r.Condition.Expression))
		cfg.WriteString(fmt.Sprintf("    action_type: %s\n", r.Action.Type))
		cfg.WriteString(fmt.Sprintf("    action_target: %s\n", r.Action.Target))
		cfg.WriteString(fmt.Sprintf("    severity: %s\n", r.Severity))
		if len(r.Params) > 0 {
			cfg.WriteString("    params:\n")
			for _, p := range r.Params {
				cfg.WriteString(fmt.Sprintf("      - { id: %s, default: %v, configurable: %v }\n", p.ID, p.Default, p.Configurable))
			}
		}
		cfg.WriteString("\n")
	}

	// Go code: RunBeforeChecks
	code.WriteString("// RunBeforeChecks runs pre-action rule checks.\n")
	code.WriteString("// Returns non-nil results if the action should be blocked or needs approval.\n")
	code.WriteString("func RunBeforeChecks(ctx context.Context, actionID string, params map[string]any) []CheckResult {\n")
	code.WriteString("\tvar results []CheckResult\n")
	code.WriteString("\tswitch actionID {\n")
	actionBefore := groupByAction(beforeRules)
	for actionID, rules := range actionBefore {
		code.WriteString(fmt.Sprintf("\tcase \"%s\":\n", actionID))
		for _, r := range rules {
			code.WriteString(fmt.Sprintf("\t\t// %s: %s\n", r.ID, r.Name))
			code.WriteString(fmt.Sprintf("\t\t// Condition: %s\n", r.Condition.Expression))
			code.WriteString(fmt.Sprintf("\t\t// Action: %s → %s\n", r.Action.Type, r.Action.Target))
			code.WriteString(fmt.Sprintf("\t\tlog.Printf(\"checking rule %s\")\n", r.ID))
			code.WriteString(fmt.Sprintf("\t\t// TODO: implement %s check\n\n", r.ID))
		}
	}
	code.WriteString("\t}\n")
	code.WriteString("\treturn results\n}\n\n")

	// Go code: RunAfterChecks
	code.WriteString("// RunAfterChecks runs post-action rule checks.\n")
	code.WriteString("func RunAfterChecks(ctx context.Context, actionID string, params map[string]any) []CheckResult {\n")
	code.WriteString("\tvar results []CheckResult\n")
	code.WriteString("\tswitch actionID {\n")
	actionAfter := groupByAction(afterRules)
	for actionID, rules := range actionAfter {
		code.WriteString(fmt.Sprintf("\tcase \"%s\":\n", actionID))
		for _, r := range rules {
			code.WriteString(fmt.Sprintf("\t\t// %s: %s\n", r.ID, r.Name))
			code.WriteString(fmt.Sprintf("\t\tlog.Printf(\"checking rule %s\")\n", r.ID))
			code.WriteString(fmt.Sprintf("\t\t// TODO: implement %s check\n\n", r.ID))
		}
	}
	code.WriteString("\t}\n")
	code.WriteString("\treturn results\n}\n\n")

	// Go code: cron rules
	if len(cronRules) > 0 {
		code.WriteString("// CronRules returns cron schedule entries for scheduled rules.\n")
		code.WriteString("func CronRules() map[string]string {\n")
		code.WriteString("\treturn map[string]string{\n")
		for _, r := range cronRules {
			code.WriteString(fmt.Sprintf("\t\t\"%s\": \"%s\", // %s\n", r.ID, r.Trigger.Cron, r.Name))
		}
		code.WriteString("\t}\n}\n")
	}

	return &Result{
		ConfigYAML: cfg.String(),
		GoCode:     code.String(),
	}
}

// groupByAction groups rules by their trigger source action IDs.
func groupByAction(rules []types.Rule) map[string][]types.Rule {
	result := make(map[string][]types.Rule)
	for _, r := range rules {
		for _, src := range r.Trigger.Source {
			src = strings.TrimSpace(src)
			result[src] = append(result[src], r)
		}
	}
	return result
}
